---
- name: Add configuration file for adduser and addgroup
  become: true
  ansible.builtin.template:
    src: "{{ adduser_conf_template }}"
    dest: /etc/adduser.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  tags:
    - adduser
    - users

- name: Add configuration file for useradd
  become: true
  ansible.builtin.template:
    src: "{{ useradd_template }}"
    dest: /etc/default/useradd
    backup: true
    mode: "0644"
    owner: root
    group: root
  tags:
    - useradd
    - users
    - CCE-27355-7
    - CCE-80954-1
    - CCE-83627-0
    - CIS-UBUNTU2004-5.5.1.4
    - UBTU-20-010409
