---
- name: Configure systemd logind
  become: true
  ansible.builtin.template:
    src: "{{ logind_conf_template }}"
    dest: /etc/systemd/logind.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd
  tags:
    - systemd
    - logind
